In [1]:
%load_ext watermark
%watermark

Last updated: 2023-06-28T11:51:44.236120-05:00

Python implementation: CPython
Python version       : 3.10.11
IPython version      : 8.13.2

Compiler    : MSC v.1916 64 bit (AMD64)
OS          : Windows
Release     : 10
Machine     : AMD64
Processor   : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
CPU cores   : 8
Architecture: 64bit

En esta sección vamos a ver diversas formas para procesar un dataset. Por procesamiento (tambien llamado limpieza) nos referimos a preparar el dataset para la creación de modelos predictivos.

#### Descripción

Vamos a usar el mismo dataset que usamos para el ejemplo de Análisis Exploratorio de Datos.

En la sección de análisis de datos, detectamos los siguientes errores en el dataset original

- Existen valores nulos los cuales es necesario rellenar
- Existen ouliners en las variables
- Es necesario eliminar aquellos registros donde la opcion seleccionada es "No responde/No sabe"

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams["figure.figsize"] = (12,12)

In [14]:
consumidores = pd.read_pickle("C:/Users/Danny/Desktop/Analisis tesis/Analisis exploratorio de datos/data/consumidores.3.variables_agrupadas.pkl")
consumidores.head()

,directorio,per_sexo,per_edad,vive_padre_hogar,vive_madre_hogar,departamento,municipio,tipo_vivienda,estrato,residentes_hogar,...,m_03_frecuencia_consumo_basuco_12m,o_02_consumio_heroina_12m,o_03_frecuencia_consumo_heroina_12m,per_edad_tipo,estrato_tipo,situacion_tipo,frecuencia_consumo_marihuana_tipo,frecuencia_consumo_cocaina_tipo,frecuencia_consumo_basuco_tipo,frecuencia_consumo_heroina_tipo
0,11207,1,19,2,2,Guaviare,SAN JOSÉ DEL GUAVIARE,2,2.0,5,...,NaN,NaN,NaN,Joven,Estrato bajo,Trabajando,Nunca,Nunca,Nunca,Nunca
1,1180,2,51,2,1,Cordoba,MONTERÍA,1,1.0,4,...,NaN,NaN,NaN,Adulto,Estrato bajo,Trabajando,Nunca,Nunca,Nunca,Nunca
2,4398,1,52,3,3,Caqueta,FLORENCIA,1,2.0,4,...,NaN,NaN,NaN,Adulto,Estrato bajo,Trabajando,Nunca,Nunca,Nunca,Nunca
3,4399,2,39,1,1,Bolivar,CARTAGENA,1,5.0,6,...,NaN,NaN,NaN,Adulto,Estrato alto,Trabajando,Nunca,Nunca,Nunca,Nunca
4,2619,2,27,1,1,Tolima,ESPINAL,1,2.0,4,...,NaN,NaN,NaN,Joven,Estrato bajo,Buscando trabajo,Nunca,Nunca,Nunca,Nunca

In [15]:
consumidores.shape

(10000, 63)

### Records duplicados

Usamos la función de pandas `drop_duplicates` para remover los records duplicados

In [16]:
consumidores[consumidores.duplicated()].shape

(0, 63)

Se puede observar que no existen registros duplicados para este dataset

### Eliminacion de columnas que yano se usaran

In [18]:
#Marihuana del capitulo g
del consumidores['g_11_f_consumio_alguna_vez_marihuana']
del consumidores['g_11_f_anios_consumio_marihuana']
#Cocaina del capitulo g
del consumidores['g_11_g_consumio_alguna_vez_cocaina']
del consumidores['g_11_g_anios_consumio_cocaina']
#Basuco del capitulo g
del consumidores['g_11_h_consumio_alguna_vez_basuco']
del consumidores['g_11_h_anios_consumio_basuco']
#Heroina del capitulo g
del consumidores['g_11_j_consumio_alguna_vez_heroina']
del consumidores['g_11_j_anios_consumio_heroina']
#Marihuana del capitulo k
del consumidores['k_03_consumio_marihuana_12m']
del consumidores['k_04_frecuencia_consumo_marihuana_12m']
#Cocaina del capitulo l
del consumidores['l_02_consumio_cocaina_12m']
del consumidores['l_03_frecuencia_consumo_cocaina_12m']
#Basuco del capitulo m
del consumidores['m_02_consumio_basuco_12m']
del consumidores['m_03_frecuencia_consumo_basuco_12m']
#Basuco del capitulo o
del consumidores['o_02_consumio_heroina_12m']
del consumidores['o_03_frecuencia_consumo_heroina_12m']

Las columnas se eliminaron debido a que son variables que fueron unidas comouna sola variable categorica,la cual sera usada
como vairable objetivo para el desarrollo del modelo

In [19]:
consumidores.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 47 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   directorio                                                 10000 non-null  int64
 1   per_sexo                                                   10000 non-null  int64
 2   per_edad                                                   10000 non-null  int64
 3   vive_padre_hogar                                           10000 non-null  int64
 4   vive_madre_hogar                                           10000 non-null  int64
 5   departamento                                               10000 non-null  object
 6   municipio                                                  10000 non-null  object
 7   tipo_vivienda                                              10000 non-null  int64
 8   estrato                                                    10000 non-null  float64
 9   residentes_hogar                                           10000 non-null  int64
 10  d_01_aporta_dinero_hogar                                   10000 non-null  int64
 11  d_02_situacion_actual                                      10000 non-null  int64
 12  d_08_estado_salud                                          10000 non-null  int64
 13  d_09_deprimido                                             10000 non-null  int64
 14  d_10_poco_interes                                          10000 non-null  int64
 15  d_11_h_conocimiento_riesgo_fumar_marihuana_frecuentemente  10000 non-null  int64
 16  d_11_k_conocimiento_riesgo_cocaina_frecuentemente          10000 non-null  int64
 17  d_11_n_conocimiento_riesgo_fumar_basuco_frecuentemente     10000 non-null  int64
 18  d_12_b_presenta_problema_consumo_sp_barrio                 10000 non-null  int64
 19  d_12_c_presenta_problema_expendio_sp_barrio                10000 non-null  int64
 20  d2_01_etnia                                                10000 non-null  int64
 21  d2_03_estado_civil                                         10000 non-null  int64
 22  d2_04_num_hijos                                            10000 non-null  int64
 23  d2_05_nivel_educativo                                      10000 non-null  int64
 24  g_01_familiares_consumen_sp                                10000 non-null  int64
 25  g_01_a_num_familiares_consumen_sp                          2747 non-null   float64
 26  g_02_amigos_consumen_sp                                    10000 non-null  int64
 27  g_02_a_num_amigos_consumen_sp                              4282 non-null   float64
 28  g_03_curiosidad_probar_sp                                  10000 non-null  int64
 29  g_04_probaria_sp                                           10000 non-null  int64
 30  g_05_posibilidad_probar_sp                                 10000 non-null  int64
 31  g_06_a_posibilidad_conseguir_marihuana                     10000 non-null  int64
 32  g_06_b_posibilidad_conseguir_cocaina                       10000 non-null  int64
 33  g_06_c_posibilidad_conseguir_basuco                        10000 non-null  int64
 34  g_06_j_posibilidad_conseguir_heroina                       10000 non-null  int64
 35  g_07_alguien_ofrecio_comprar_probar_sp                     10000 non-null  int64
 36  g_08_a_ofrecieron_marihuana                                4866 non-null   float64
 37  g_08_b_ofrecieron_cocaina                                  4866 non-null   float64
 38  g_08_c_ofrecieron_basuco                                   4866 non-null   float64
 39  g_08_e_ofrecieron_heroina                                  4866 non-null   float64
 40  per_edad_tipo                                              10000 non-null  category
 41  estrato_tipo                                               10000 non-null  category
 42  situacion_tipo                                             10000 non-null  category
 43  frecuencia_consumo_marihuana_tipo                          10000 non-null  category
 44  frecuencia_consumo_cocaina_tipo                            10000 non-null  category
 45  frecuencia_consumo_basuco_tipo                             10000 non-null  category
 46  frecuencia_consumo_heroina_tipo                            10000 non-null  category
dtypes: category(7), float64(7), int64(31), object(2)
memory usage: 3.1+ MB

In [21]:
consumidores.shape

(10000, 47)

### Valores Extremos (outliers)

In [20]:
from scipy import stats
import numpy as np

def outliers_col(df):
    for columna in df:
        if df[columna].dtype != np.object_:
            n_outliers = len(df[np.abs(stats.zscore(df[columna])) > 3])    
            print("{} | {} | {}".format(
                df[columna].name,
                n_outliers,
                df[columna].dtype
        ))

#outliers_col(consumidores)

In [9]:
consumidores.describe()

,directorio,per_sexo,per_edad,vive_padre_hogar,vive_madre_hogar,tipo_vivienda,servicio_energia,estrato,residentes_hogar,d_01_aporta_dinero_hogar,...,g_11_j_consumio_alguna_vez_heroina,g_11_j_anios_consumio_heroina,k_03_consumio_marihuana_12m,k_04_frecuencia_consumo_marihuana_12m,l_02_consumio_cocaina_12m,l_03_frecuencia_consumo_cocaina_12m,m_02_consumio_basuco_12m,m_03_frecuencia_consumo_basuco_12m,o_02_consumio_heroina_12m,o_03_frecuencia_consumo_heroina_12m
count,10149.000000,10149.000000,10149.000000,10149.000000,10149.000000,10149.000000,10149.000000,10127.000000,10149.000000,10149.000000,...,10149.000000,49.000000,3982.000000,1223.000000,973.000000,248.000000,310.000000,57.000000,49.000000,5.000000
mean,17264.954577,1.496207,36.319736,2.130456,1.867376,1.482806,1.002168,2.186630,3.389004,1.306237,...,1.995172,19.693878,1.701657,3.312347,1.773895,2.685484,1.838710,3.368421,1.897959,2.400000
std,16871.693694,0.500010,14.402560,0.642049,0.668973,0.555924,0.046510,1.068615,1.725787,0.460952,...,0.069320,8.073114,0.528887,1.515518,0.636878,1.393257,0.562977,1.276597,0.305839,1.516575
min,2.000000,1.000000,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,5268.000000,1.000000,24.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,...,2.000000,16.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,10554.000000,1.000000,34.000000,2.000000,2.000000,1.000000,1.000000,2.000000,3.000000,1.000000,...,2.000000,18.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000
75%,25465.000000,2.000000,48.000000,3.000000,2.000000,2.000000,1.000000,3.000000,4.000000,2.000000,...,2.000000,21.000000,2.000000,5.000000,2.000000,4.000000,2.000000,5.000000,2.000000,2.000000
max,59973.000000,2.000000,65.000000,3.000000,3.000000,4.000000,2.000000,9.000000,14.000000,2.000000,...,2.000000,58.000000,9.000000,9.000000,9.000000,9.000000,9.000000,5.000000,2.000000,5.000000

In [14]:
vehiculos.shape

(36185, 11)

### Valores inexistentes

In [22]:
n_records = len(consumidores)
def valores_inexistentes_col(df):
    for columna in df:
        print("{} | {} | {}".format(
            df[columna].name, len(df[df[columna].isnull()]) / (1.0*n_records), df[columna].dtype
        ))

valores_inexistentes_col(consumidores)

directorio | 0.0 | int64
per_sexo | 0.0 | int64
per_edad | 0.0 | int64
vive_padre_hogar | 0.0 | int64
vive_madre_hogar | 0.0 | int64
departamento | 0.0 | object
municipio | 0.0 | object
tipo_vivienda | 0.0 | int64
estrato | 0.0 | float64
residentes_hogar | 0.0 | int64
d_01_aporta_dinero_hogar | 0.0 | int64
d_02_situacion_actual | 0.0 | int64
d_08_estado_salud | 0.0 | int64
d_09_deprimido | 0.0 | int64
d_10_poco_interes | 0.0 | int64
d_11_h_conocimiento_riesgo_fumar_marihuana_frecuentemente | 0.0 | int64
d_11_k_conocimiento_riesgo_cocaina_frecuentemente | 0.0 | int64
d_11_n_conocimiento_riesgo_fumar_basuco_frecuentemente | 0.0 | int64
d_12_b_presenta_problema_consumo_sp_barrio | 0.0 | int64
d_12_c_presenta_problema_expendio_sp_barrio | 0.0 | int64
d2_01_etnia | 0.0 | int64
d2_03_estado_civil | 0.0 | int64
d2_04_num_hijos | 0.0 | int64
d2_05_nivel_educativo | 0.0 | int64
g_01_familiares_consumen_sp | 0.0 | int64
g_01_a_num_familiares_consumen_sp | 0.7253 | float64
g_02_amigos_consumen_sp | 0.0 | int64
g_02_a_num_amigos_consumen_sp | 0.5718 | float64
g_03_curiosidad_probar_sp | 0.0 | int64
g_04_probaria_sp | 0.0 | int64
g_05_posibilidad_probar_sp | 0.0 | int64
g_06_a_posibilidad_conseguir_marihuana | 0.0 | int64
g_06_b_posibilidad_conseguir_cocaina | 0.0 | int64
g_06_c_posibilidad_conseguir_basuco | 0.0 | int64
g_06_j_posibilidad_conseguir_heroina | 0.0 | int64
g_07_alguien_ofrecio_comprar_probar_sp | 0.0 | int64
g_08_a_ofrecieron_marihuana | 0.5134 | float64
g_08_b_ofrecieron_cocaina | 0.5134 | float64
g_08_c_ofrecieron_basuco | 0.5134 | float64
g_08_e_ofrecieron_heroina | 0.5134 | float64
per_edad_tipo | 0.0 | category
estrato_tipo | 0.0 | category
situacion_tipo | 0.0 | category
frecuencia_consumo_marihuana_tipo | 0.0 | category
frecuencia_consumo_cocaina_tipo | 0.0 | category
frecuencia_consumo_basuco_tipo | 0.0 | category
frecuencia_consumo_heroina_tipo | 0.0 | category

Muchos algoritmos de Machine Learning requieren que no existan valores inexistentes (o NaN como se llaman a veces).

Hay varias técnicas para tratar dichos valores:

Reemplazar los valores inexistentes con un valor en particular. Por ejemplo 0 o "null" Es una forma simple de tratar estos valores pero añade un monton de ruido (asume que los valores inexistentes lo son por un motivo en concreto)

In [24]:
consumidores["g_01_a_num_familiares_consumen_sp_imp"] = consumidores.g_01_a_num_familiares_consumen_sp.fillna(3)
consumidores["g_02_a_num_amigos_consumen_sp_imp"] = consumidores.g_02_a_num_amigos_consumen_sp.fillna(3)

consumidores["g_08_a_ofrecieron_marihuana_imp"] = consumidores.g_08_a_ofrecieron_marihuana.fillna(10)
consumidores["g_08_b_ofrecieron_cocaina_imp"] = consumidores.g_08_b_ofrecieron_cocaina.fillna(10)
consumidores["g_08_c_ofrecieron_basuco_imp"] = consumidores.g_08_c_ofrecieron_basuco.fillna(10)
consumidores["g_08_e_ofrecieron_heroina_imp"] = consumidores.g_08_e_ofrecieron_heroina.fillna(10)


consumidores.shape

(10000, 53)

Con los datos imputados ahora se procede a eliminar las vairables que han sido imputadas para asi poder eliminar el porcentaje de valores nulos que existen

In [25]:
del consumidores['g_01_a_num_familiares_consumen_sp']
del consumidores['g_02_a_num_amigos_consumen_sp']
del consumidores['g_08_a_ofrecieron_marihuana']
del consumidores['g_08_b_ofrecieron_cocaina']
del consumidores['g_08_c_ofrecieron_basuco']
del consumidores['g_08_e_ofrecieron_heroina']

consumidores.shape

(10000, 47)

In [28]:
consumidores.g_01_a_num_familiares_consumen_sp_imp = consumidores.g_01_a_num_familiares_consumen_sp_imp.astype("int64")
consumidores.g_02_a_num_amigos_consumen_sp_imp = consumidores.g_02_a_num_amigos_consumen_sp_imp.astype("int64")
consumidores.g_08_a_ofrecieron_marihuana_imp = consumidores.g_08_a_ofrecieron_marihuana_imp.astype("int64")
consumidores.g_08_b_ofrecieron_cocaina_imp = consumidores.g_08_b_ofrecieron_cocaina_imp.astype("int64")
consumidores.g_08_c_ofrecieron_basuco_imp = consumidores.g_08_c_ofrecieron_basuco_imp.astype("int64")
consumidores.g_08_e_ofrecieron_heroina_imp = consumidores.g_08_e_ofrecieron_heroina_imp.astype("int64")

In [29]:
valores_inexistentes_col(consumidores)

directorio | 0.0 | int64
per_sexo | 0.0 | int64
per_edad | 0.0 | int64
vive_padre_hogar | 0.0 | int64
vive_madre_hogar | 0.0 | int64
departamento | 0.0 | object
municipio | 0.0 | object
tipo_vivienda | 0.0 | int64
estrato | 0.0 | float64
residentes_hogar | 0.0 | int64
d_01_aporta_dinero_hogar | 0.0 | int64
d_02_situacion_actual | 0.0 | int64
d_08_estado_salud | 0.0 | int64
d_09_deprimido | 0.0 | int64
d_10_poco_interes | 0.0 | int64
d_11_h_conocimiento_riesgo_fumar_marihuana_frecuentemente | 0.0 | int64
d_11_k_conocimiento_riesgo_cocaina_frecuentemente | 0.0 | int64
d_11_n_conocimiento_riesgo_fumar_basuco_frecuentemente | 0.0 | int64
d_12_b_presenta_problema_consumo_sp_barrio | 0.0 | int64
d_12_c_presenta_problema_expendio_sp_barrio | 0.0 | int64
d2_01_etnia | 0.0 | int64
d2_03_estado_civil | 0.0 | int64
d2_04_num_hijos | 0.0 | int64
d2_05_nivel_educativo | 0.0 | int64
g_01_familiares_consumen_sp | 0.0 | int64
g_02_amigos_consumen_sp | 0.0 | int64
g_03_curiosidad_probar_sp | 0.0 | int64
g_04_probaria_sp | 0.0 | int64
g_05_posibilidad_probar_sp | 0.0 | int64
g_06_a_posibilidad_conseguir_marihuana | 0.0 | int64
g_06_b_posibilidad_conseguir_cocaina | 0.0 | int64
g_06_c_posibilidad_conseguir_basuco | 0.0 | int64
g_06_j_posibilidad_conseguir_heroina | 0.0 | int64
g_07_alguien_ofrecio_comprar_probar_sp | 0.0 | int64
per_edad_tipo | 0.0 | category
estrato_tipo | 0.0 | category
situacion_tipo | 0.0 | category
frecuencia_consumo_marihuana_tipo | 0.0 | category
frecuencia_consumo_cocaina_tipo | 0.0 | category
frecuencia_consumo_basuco_tipo | 0.0 | category
frecuencia_consumo_heroina_tipo | 0.0 | category
g_01_a_num_familiares_consumen_sp_imp | 0.0 | int64
g_02_a_num_amigos_consumen_sp_imp | 0.0 | int64
g_08_a_ofrecieron_marihuana_imp | 0.0 | int64
g_08_b_ofrecieron_cocaina_imp | 0.0 | int64
g_08_c_ofrecieron_basuco_imp | 0.0 | int64
g_08_e_ofrecieron_heroina_imp | 0.0 | int64

Otras técnicas incluyen:


- Usar un modelo predictivo para predecir los valores inexistentes, usando como informacion los records con la informacion completa

- Metodos más sofisticados: [MICE](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3074241/), en este [repositorio](https://github.com/hammerlab/fancyimpute) hay mas métodos

[Aqui](https://gallery.cortanaintelligence.com/Experiment/Methods-for-handling-missing-values-1) hay mas estrategias

Finalmente, guardamos a csv o pkl el dataset limpio

In [30]:
consumidores.to_pickle("C:/Users/Danny/Desktop/Analisis tesis/Analisis exploratorio de datos/data/consumidores_procesado.pkl")
consumidores.to_csv("C:/Users/Danny/Desktop/Analisis tesis/Analisis exploratorio de datos/data/consumidores_procesado.csv", index=False)

### links

http://sebastianraschka.com/Articles/2014_about_feature_scaling.html#about-standardization